### ISSUE TITLE
similar components are duplicated across the app

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [STAPLE-verse/STAPLE#102]
The elementId page uses similar widgets to the taskId page. I did not know about this before. It would be nice to use the same components across different contexts if they provide the same functionality. 

After the MVP is out we should sit down and map out these components and refactor them for easier maintenance.

@doomlab

**Comment by doomlab** [comment]
@marton-balazs-kovacs - did you take care of this stuff in your recent cleanup?

**Comment by doomlab** [comment]
I believe much of this has been cleaned up with the rewrite - let's make specific issues for specific components when we find them.
