### ISSUE TITLE
Tanstack search/filter on paginated pages

### ISSUE THREAD

**Issue by doomlab** [STAPLE-verse/STAPLE#109]
The search / filter options with tanstack only show you stuff on that page, see if there's a way to search across paginated queries. .

**Comment by marton-balazs-kovacs** [comment]
partially fixed in #251 

tables that use data fetched by paginated query needs to be updated to fetch all data and table component call needs to be updated to call for a paginated table

**Comment by doomlab** [comment]
pages with search filtering:
- [ ] projects page: this is a different filtering not tanstack so it works fine
- [ ] invitations page 
- [ ] tasks page: looks like marton has fixed this one
- [ ] notifications
- [ ] forms 
- [ ] roles
- [ ] elements (add search like projects page)
- [ ] project task table: also probably fixed
- [ ] contributors
- [ ] teams
- [ ] form data
- [ ] project notifications
- [ ] roles pages
