### ISSUE TITLE
Making tasks droppable and sortable within elements

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [STAPLE-verse/STAPLE#12]
I created the ElementList component with a basic setup of drag and drop using dndkit, however, the functionality is not fully fleshed out. It would be great if tasks could be assigned to new elements on this page by using the drag and drop functionality. Also, users should be able to rearrange tasks within elements.

Idea: Have a button for each element on this page so that tasks that are not assigned to elements can be added here as well, so users do not have to open the specific task they want to add and update it.

**Comment by doomlab** [comment]
given the new table on our element view, this point may be mute
