### ISSUE TITLE
table buttons

### ISSUE THREAD

**Issue by doomlab** [STAPLE-verse/STAPLE#200]
Buttons with small icons, just a personal preference, for example instead of several times creating a button with the text “View”, I would do a open folder or magnifier symbol. I just think you have too many buttons on some pages and some icons would help.

**Comment by marton-balazs-kovacs** [comment]
I think this is a good idea if users know what we mean by the icons. This is someone that we can user test with the help of the UX team. Happy to change them if that is what people want.

**Comment by doomlab** [comment]
This was updated in the database change to make the tables more concise.
