### ISSUE TITLE
tanstack filtering is weird

### ISSUE THREAD

**Issue by doomlab** [STAPLE-verse/STAPLE#201]
<img width="286" alt="image" src="https://github.com/user-attachments/assets/23feddfb-a299-432c-b4f4-440d8fa13bf8">

<img width="436" alt="image" src="https://github.com/user-attachments/assets/f6aa6b0d-1700-4a20-89ce-6d7c1dd60478">

**Comment by marton-balazs-kovacs** [comment]
This is due to how _"src/core/components/TextFilter.tsx"_ is being set up. The search works with strings but not with objects or HTML formatted code.

**Comment by marton-balazs-kovacs** [comment]
Some of this is fixed in PR #251 but other table column definitions are needed to be updated accordingly to:

- ensure that preprocessed data are passed to the table
- tpyes are matching
- proper filter types are used
- no filtering for passed objects if passing objects is necessary
