### ISSUE TITLE
should the top nav bar notifications change while you are in a project? 

### ISSUE THREAD

**Issue by doomlab** [STAPLE-verse/STAPLE#202]
<img width="1503" alt="image" src="https://github.com/user-attachments/assets/c9f5e0c9-e4df-442c-a68a-a9bd838d43c1">

**Comment by marton-balazs-kovacs** [comment]
For me, the top navbar notification counter shows all the notifications regardless of which project you are in. I think this is the desired behavior since the top navbar is project agnostic and the sidebar changes dynamically with the project.

**Comment by doomlab** [comment]
sounds great
