### ISSUE TITLE
elements update

### ISSUE THREAD

**Issue by doomlab** [STAPLE-verse/STAPLE#203]
What would be maybe convenient, that when you create an Element you could also add Tasks with a picker or some selection. Maybe you already created a few tasks and want to add them to one new element. Else you need to go to every task and select the element.

Above I wrote about selecting elements in tasks. I don't know about the elements overview. I can not open an element right away, can not sort or filter the list of elements. Maybe a list / table view would be good, where you can sort and filter it like with the tasks table, you could even write some status in the list

**Comment by marton-balazs-kovacs** [comment]
The first paragraph of the issue is already implemented on main.

I do not know about the second part. We decided to keep the current overview for the element overview page as you can put more information on the page with a table. We can change that later if more users want to have it that way.

**Comment by doomlab** [comment]
Added in #269
