### ISSUE TITLE
Checkbox field styling inconsistency

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [STAPLE-verse/STAPLE#212]
_"/src/core/components/fields/CheckboxFieldTable.tsx"_ does not have styled checkboxes like _"src/teams/components/TeamMembersTable.tsx"_ does. We should fix _CheckboxFieldTable.tsx_ and reuse it for _TeamMembersTable.tsx_.

**Comment by doomlab** [comment]
fixed with #238
