### ISSUE TITLE
new element description also required

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [STAPLE-verse/STAPLE#217]
On creating a new element there is no required text next to the description but it is required. @doomlab should it be required or not?

**Comment by doomlab** [comment]
... I missed that then ... this is the only place we require a description, what do you think?

**Comment by marton-balazs-kovacs** [comment]
I think it is fine to leave it optional then. I will remove it from the schema.

**Comment by marton-balazs-kovacs** [comment]
fixed this and not working element update but pushed to main by mistake: 4f73e571a319af313993ecbd349eebc50db0aacc

although it was already fixed by me in #224

**Comment by doomlab** [comment]
Tested - can add with no description
