### ISSUE TITLE
Tasks table view

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [STAPLE-verse/STAPLE#28]
TaskTable component has to be updated to be pretty, have links to the tasks pages, and rerender when new tasks are added.

When a new task is added to a project, the TaskTable component does not update automatically on the AllTaskPage view but the page has to be refreshed to show the new task in the table. Rerender button does not work.

**Comment by doomlab** [comment]
This appears to be fixed - partially because of the routes you have to take to get back to tasks, it definitely has a refresh.
