### ISSUE TITLE
Unit Test (Components)

### ISSUE THREAD

**Issue by enyeal** [STAPLE-verse/STAPLE#284]
Unit Test
These are the components to tackle first.

- [x] ShowTeamModal
- [x]  TaskCard
- [x]  TaskInput
- [x]  AllLabelList
- [x]  TaskView
- [x]  dateformat
- [x]  datefield
- [x]  labelview 
- [x]  elementview
- [x]  projectMemberView
- [x]  teamView
- [x]  labeledTestField
- [x]  labeledPassword

LabelAddTableModal

Things to consider:
- Each "Unit Test" should have a branch

**Comment by enyeal** [comment]
Other things to consider:
- Shell Script, to count the components
- Each 'Unit Test' should have a branch

**Comment by doomlab** [comment]
- [ ] src > core > components > jsonformmodal - testing the json form component to make sure it renders with a schema/ui/data put into it
- [ ] src > invites > components > inviteslist (QUERY)

**Comment by doomlab** [comment]
These are completed!
