### ISSUE TITLE
Assign user who created the task as a contributor to the task automatically

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [STAPLE-verse/STAPLE#29]
I think the user who creates the task should be assigned to the task automatically. This way we can make sure that we track the project management contributions of a user. This type of contribution would be considered "Project administration" according to the CRediT taxonomy.

Also, if there are multiple PMs on a project by tracking which PM created which tasks we can make sure that contributors to a given task know who to reach out to if they have questions regarding the task they had been assigned to.

**Comment by doomlab** [comment]
With the new tables that we have the person's name who created it, so I think this is somewhat covered.
