### ISSUE TITLE
On Summary UtilsView/TaskView

### ISSUE THREAD

**Issue by enyeal** [STAPLE-verse/STAPLE#314]
needs to check that assignee is less than 1 and not zero

**Comment by doomlab** [comment]
Hey @enyeal --> did we fix this with our database query fix?

**Comment by enyeal** [comment]
No, it is still there in the dev branch.
This the line that needs to be change:
https://github.com/STAPLE-verse/STAPLE/blob/117f8f4fac92887eb66457e8c6f853d3062b696b/src/summary/components/UtilsViews.tsx#L55

**Comment by doomlab** [comment]
fixed with restructure of project summary
