### ISSUE TITLE
automatic CI to preview dev deployment

### ISSUE THREAD

**Issue by marton-balazs-kovacs** [STAPLE-verse/STAPLE#97]
Looks good to me - I did not notice anything out of the ordinary while reviewing.

What would help build confidence in the review process is to have automated preview deployments - this would help see whether there's any critical errors being introduced (I don't suspect here but I too overlook things).

_Originally posted by @chartgerink in https://github.com/STAPLE-verse/STAPLE/pull/90#pullrequestreview-2107212727_

**Comment by doomlab** [comment]
Somewhat solved with the automatic CI deployment.
